source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’10.0’
use_frameworks!

target 'RestShip_Example' do
  pod 'RestShip', :path => '../'
end

target 'RestShip_Tests' do
  pod 'RestShip', :path => '../'

  
end
